### ISSUE TITLE
Breaks Fedora 35

### ISSUE THREAD

**Issue by jeffclay** [negativo17/gstreamer1-plugins-bad#6]
On a fresh install of Fedora 35, perform all updates, install the negativo17 multimedia repo then run updates again.
The issue is when the gstreamer1-plugins replace existing system packages.
There will be multiple processes of 'gs-plugin-scanner' spawned (it starts as a single process and gradually increases).
gnome-control-panel aka Settings and other apps stop working.

**Comment by scaronni** [comment]
Sorry I can't reproduce. Any other hint? Is it still happening?
